### ISSUE TITLE
Robintrack Popularity History compressed file is corrupted while the archive generates

### ISSUE THREAD

**Issue by skapoor-coatue** [Ameobea/robintrack#82]
[Robintrack Popularity History](https://robintrack-data.ameo.design/robintrack-popularity-history.tar.xz) seems corrupted. Could you please investigate this issue?

**Comment by Ameobea** [comment]
Hey,

I just downloaded and extracted the file without issue.  What program/tool are you using to try to extract it?

**Comment by jasonge27** [comment]
Hi @Ameobea I am having the same issue. I'm running in Mac OS 10.15.5. I ran `tar -xvf robintrack-popularity-history.tar.xz` and it failed with 
```
Lzma library error:  No progress is possible
tar: Error exit delayed from previous errors.
```
also my tar version info:
```
$tar --version
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6
```

**Comment by jasonge27** [comment]
The unzipping works fine today. The issue seems to be transient

**Comment by Ameobea** [comment]
I think that the issue is that I generate the archive directly into the web serving directory, so it's possible that people can download it while it's only partially written.  The chance of this happening went up significantly as I switched from .gz to .xz compression; .xz takes WAY longer to compress.

I can fix this by generating the archive fully and only then moving it to the web serving directory - my bad!  I'll make that fix shortly

**Comment by skapoor-coatue** [comment]
Thanks for putting back the .gz file. The issue seems to be resolved now.

**Comment by Ameobea** [comment]
Things are still broken here; I have to adjust the scripts to deal with the new database architecture I've set up to deal with increased load.  I'm going to switch back to .tar.gz anyway I think

**Comment by xyjprc** [comment]
Link on the website download page is still pointing to the corrupt .tar.xz

**Comment by Ameobea** [comment]
I've updated the data export script to work with the latest changes to hardware configuration and database setup and altered the script that prepares the archive to only place the archive in the web serving directly once it's fully generated.  This should fix this issue and all other export-related problems.

Please let me know if that's not the case though; I'll be keeping an eye on this over the next days to make sure the fix is complete and stable!

**Comment by xyjprc** [comment]
@Ameobea The popularity history gz file is now stale; latest date is July 18.

**Comment by Ameobea** [comment]
Damn it, I'll look into this...

**Comment by Ameobea** [comment]
I made a silly configuration mistake that was causing the script not to run; the script itself works fine and I have just finished a manual run of it.  Ty for letting me know!

**Comment by xyjprc** [comment]
Thank you, unfortunately still broken, the contents of the gz file is empty.
